# Base image
FROM python:3.12-slim

ENV PYTHONUNBUFFERED=1

WORKDIR /app

# Install system dependencies
RUN apt-get update && \
    apt-get install -y \
        build-essential \
        cmake \
        ninja-build \
        git \
        libssl-dev \
        python3-dev

# Install liboqs-python
RUN git clone --branch main https://github.com/open-quantum-safe/liboqs-python.git /tmp/liboqs-python && \
    cd /tmp/liboqs-python && \
    pip install . && \
    rm -rf /tmp/liboqs-python

# Install Python packages
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# Copy project
COPY . .

EXPOSE 8501

CMD ["streamlit","run","dashboard.py","--server.address=0.0.0.0","--server.port=8501"]